apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-container
        image: JoseCorreaV/devops-test-web:latest
        ports:
        - containerPort: 8080
        env:
        - name: HOST_REDIS
          value: redis